-- MySQL Script generated by MySQL Workbench
-- Fri Nov  9 15:39:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema University-DB
-- -----------------------------------------------------
-- Computer Science 430 - Final Project University Database

-- -----------------------------------------------------
-- Schema University-DB
--
-- Computer Science 430 - Final Project University Database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `University-DB` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `University-DB` ;

-- -----------------------------------------------------
-- Table `University-DB`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University-DB`.`Professor` (
  `ssn` INT(10) NOT NULL,
  `name` VARCHAR(45) NULL,
  `age` INT(3) NULL,
  `rank` VARCHAR(45) NULL,
  `speciality` VARCHAR(64) NULL,
  PRIMARY KEY (`ssn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University-DB`.`Deptartment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University-DB`.`Deptartment` (
  `dNumber` INT NOT NULL,
  `dname` VARCHAR(45) NULL,
  `office` VARCHAR(45) NULL,
  PRIMARY KEY (`dNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University-DB`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University-DB`.`Project` (
  `pid` INT NOT NULL,
  `sponsor` VARCHAR(45) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `budget` DOUBLE NULL,
  PRIMARY KEY (`pid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University-DB`.`Graduate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University-DB`.`Graduate` (
  `ssn` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `age` INT(3) NULL,
  PRIMARY KEY (`ssn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University-DB`.`Work_proj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University-DB`.`Work_proj` (
  `Graduate_ssn` INT NOT NULL,
  `Project_pid` INT NOT NULL,
  PRIMARY KEY (`Graduate_ssn`, `Project_pid`),
  INDEX `fk_Work_proj_Project1_idx` (`Project_pid` ASC) VISIBLE,
  CONSTRAINT `fk_Work_proj_Graduate`
    FOREIGN KEY (`Graduate_ssn`)
    REFERENCES `University-DB`.`Graduate` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Work_proj_Project1`
    FOREIGN KEY (`Project_pid`)
    REFERENCES `University-DB`.`Project` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University-DB`.`Runs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University-DB`.`Runs` (
  `Deptartment_dNumber` INT NOT NULL,
  `Professor_ssn` INT NOT NULL,
  PRIMARY KEY (`Deptartment_dNumber`, `Professor_ssn`),
  INDEX `fk_Runs_Professor1_idx` (`Professor_ssn` ASC) VISIBLE,
  CONSTRAINT `fk_Runs_Deptartment1`
    FOREIGN KEY (`Deptartment_dNumber`)
    REFERENCES `University-DB`.`Deptartment` (`dNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Runs_Professor1`
    FOREIGN KEY (`Professor_ssn`)
    REFERENCES `University-DB`.`Professor` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University-DB`.`Work_Dept`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University-DB`.`Work_Dept` (
  `Professor_ssn` INT(10) NOT NULL,
  `Deptartment_dNumber` INT NOT NULL,
  `pc_time` VARCHAR(45) NULL,
  PRIMARY KEY (`Professor_ssn`, `Deptartment_dNumber`),
  INDEX `fk_Work_Dept_Deptartment1_idx` (`Deptartment_dNumber` ASC) VISIBLE,
  CONSTRAINT `fk_Work_Dept_Professor1`
    FOREIGN KEY (`Professor_ssn`)
    REFERENCES `University-DB`.`Professor` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Work_Dept_Deptartment1`
    FOREIGN KEY (`Deptartment_dNumber`)
    REFERENCES `University-DB`.`Deptartment` (`dNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University-DB`.`Major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University-DB`.`Major` (
  `Graduate_ssn` INT NOT NULL,
  `Deptartment_dNumber` INT NOT NULL,
  PRIMARY KEY (`Graduate_ssn`, `Deptartment_dNumber`),
  INDEX `fk_Major_Deptartment1_idx` (`Deptartment_dNumber` ASC) VISIBLE,
  CONSTRAINT `fk_Major_Graduate1`
    FOREIGN KEY (`Graduate_ssn`)
    REFERENCES `University-DB`.`Graduate` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Major_Deptartment1`
    FOREIGN KEY (`Deptartment_dNumber`)
    REFERENCES `University-DB`.`Deptartment` (`dNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University-DB`.`Supervises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University-DB`.`Supervises` (
  `Professor_ssn` INT NOT NULL,
  `Project_pid` INT NOT NULL,
  `Graduate_ssn` INT NOT NULL,
  PRIMARY KEY (`Professor_ssn`, `Project_pid`, `Graduate_ssn`),
  INDEX `fk_Supervises_Project1_idx` (`Project_pid` ASC) VISIBLE,
  INDEX `fk_Supervises_Graduate1_idx` (`Graduate_ssn` ASC) VISIBLE,
  CONSTRAINT `fk_Supervises_Professor1`
    FOREIGN KEY (`Professor_ssn`)
    REFERENCES `University-DB`.`Professor` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supervises_Project1`
    FOREIGN KEY (`Project_pid`)
    REFERENCES `University-DB`.`Project` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supervises_Graduate1`
    FOREIGN KEY (`Graduate_ssn`)
    REFERENCES `University-DB`.`Graduate` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University-DB`.`Manages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University-DB`.`Manages` (
  `Professor_ssn` INT NOT NULL,
  `Project_pid` INT NOT NULL,
  PRIMARY KEY (`Professor_ssn`, `Project_pid`),
  INDEX `fk_Manages_Project1_idx` (`Project_pid` ASC) VISIBLE,
  CONSTRAINT `fk_Manages_Professor1`
    FOREIGN KEY (`Professor_ssn`)
    REFERENCES `University-DB`.`Professor` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Manages_Project1`
    FOREIGN KEY (`Project_pid`)
    REFERENCES `University-DB`.`Project` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University-DB`.`Work_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `University-DB`.`Work_in` (
  `Professor_ssn` INT NOT NULL,
  `Project_pid` INT NOT NULL,
  PRIMARY KEY (`Professor_ssn`, `Project_pid`),
  INDEX `fk_Work_in_Project1_idx` (`Project_pid` ASC) VISIBLE,
  CONSTRAINT `fk_Work_in_Professor1`
    FOREIGN KEY (`Professor_ssn`)
    REFERENCES `University-DB`.`Professor` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Work_in_Project1`
    FOREIGN KEY (`Project_pid`)
    REFERENCES `University-DB`.`Project` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table 'University-DB'.'db-users'
-- -----------------------------------------------------
CREATE TABLE `university-db`.`db-users` (
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE);

CREATE USER 'admin' IDENTIFIED BY 'admin';

GRANT ALL ON `University-DB`.* TO 'admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
